name: Generate ASCII Artwork

on:
  push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

<<<<<<< HEAD
      - name: Upload Dragon text file
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file
          path: dragon.txt
=======
 
>>>>>>> 8567797172ccf36440198243a33efd85c8cb7535

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    needs: [test_job2]
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Download Dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

=======
      - name: Download Dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file
          
>>>>>>> 8567797172ccf36440198243a33efd85c8cb7535
      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ... ... .