name: Exploring Variables and Secrets

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/1 * * * *"
    # push

env:
    CONTAINER_REGISTERY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $ {{ env.CONTAINER_REGISTERY  }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker Login
          run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest



    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: |
            echo docker -d -p 8080:80 $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            sleep 600s